---
title: "CodeBook"
date: "September 3, 2017"
output: html_document
---

## Code Book to Coursera Week 4 programming assignment
======================================================

Codebook was generated on `r as.character(Sys.time())`.

List of Variables and Descriptions
------------------------------

subject:- Values range from 1 to 30. This field IDs the subject who performed the activity.
activity:- Name of the activity
featDomain:- Feature: Time domain signal or frequency domain signal (Time or Freq)
featInstrument:- Feature: Measuring instrument (Accelerometer or Gyroscope)
featAcceleration:- Feature: Acceleration signal (Body or Gravity)
featVariable:- Feature: Variable (Mean or SD)
featJerk:- Feature: Jerk signal
featMagnitude:- Feature: Magnitude of the signals calculated using the Euclidean norm
featAxis:- Feature: 3-axial signals in the X, Y and Z directions (X, Y, or Z)
featCount:- Feature: Count of data points used to compute `average`
featAverage:- Feature: Average of each variable for each activity and each subject

Indepth information on the tidy data
------------------------------------

```{r}
str(tidyAverageData)
```

Data table variables
--------------------

```{r}
key(tidyAverageData)
```

Sample rows of tidy data 
------------------------

```{r}
head(tidyAverageData)
```

Summary of variables
--------------------

```{r}
summary(tidyAverageData)
```